/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tratamientotexto;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author JaimeRodríguezGutiér
 */
public class TratamientoDeTexto extends javax.swing.JFrame {
    private Font font;

    /**
     * Creates new form TratamientoDeTexto
     */
    public TratamientoDeTexto() {
        initComponents();
        font = new Font("SegoeUI",Font.PLAIN,12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFondo = new javax.swing.ButtonGroup();
        bgAlineacion = new javax.swing.ButtonGroup();
        bAutor = new javax.swing.JButton();
        rbRojo = new javax.swing.JRadioButton();
        rbVerde = new javax.swing.JRadioButton();
        rbIzquierda = new javax.swing.JRadioButton();
        rbCentro = new javax.swing.JRadioButton();
        rbDerecha = new javax.swing.JRadioButton();
        cbCursiva = new javax.swing.JCheckBox();
        cbNegrita = new javax.swing.JCheckBox();
        lTitulo = new javax.swing.JLabel();
        etNombre = new javax.swing.JTextField();
        lFondo = new javax.swing.JLabel();
        lAlineacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bAutor.setText("Autor");
        bAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAutorActionPerformed(evt);
            }
        });

        bgFondo.add(rbRojo);
        rbRojo.setText("Rojo");
        rbRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRojoActionPerformed(evt);
            }
        });

        bgFondo.add(rbVerde);
        rbVerde.setText("Verde");
        rbVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerdeActionPerformed(evt);
            }
        });

        bgAlineacion.add(rbIzquierda);
        rbIzquierda.setText("Izq");
        rbIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIzquierdaActionPerformed(evt);
            }
        });

        bgAlineacion.add(rbCentro);
        rbCentro.setText("Centro");
        rbCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCentroActionPerformed(evt);
            }
        });

        bgAlineacion.add(rbDerecha);
        rbDerecha.setText("Derech");
        rbDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDerechaActionPerformed(evt);
            }
        });

        cbCursiva.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cbCursiva.setText("Cursiva");
        cbCursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursivaActionPerformed(evt);
            }
        });

        cbNegrita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbNegrita.setText("Negrita");
        cbNegrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNegritaActionPerformed(evt);
            }
        });

        lTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lTitulo.setText("TRATAMIENTO DE TEXTO");
        lTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        etNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNombreActionPerformed(evt);
            }
        });

        lFondo.setText("FONDO");

        lAlineacion.setText("ALINEACION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCursiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(etNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbRojo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rbVerde)
                                            .addGap(81, 81, 81)
                                            .addComponent(rbIzquierda))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(lFondo)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lAlineacion)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbCentro)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rbDerecha)))))
                            .addComponent(cbNegrita))
                        .addContainerGap(37, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTitulo)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFondo)
                    .addComponent(lAlineacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRojo)
                    .addComponent(rbVerde)
                    .addComponent(rbIzquierda)
                    .addComponent(rbCentro)
                    .addComponent(rbDerecha))
                .addGap(44, 44, 44)
                .addComponent(cbNegrita)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(bAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCursiva))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etNombreActionPerformed

    private void rbRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRojoActionPerformed
        // TODO add your handling code here:
        if(rbRojo.isSelected()){
            etNombre.setBackground(Color.red);
        }
    }//GEN-LAST:event_rbRojoActionPerformed

    private void rbVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerdeActionPerformed
        // TODO add your handling code here:
        if(rbVerde.isSelected()){
            etNombre.setBackground(Color.green);
        }
    }//GEN-LAST:event_rbVerdeActionPerformed

    private void rbIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIzquierdaActionPerformed
        // TODO add your handling code here:
        if(rbIzquierda.isSelected()){
           etNombre.setHorizontalAlignment(etNombre.LEFT);
        }  
    }//GEN-LAST:event_rbIzquierdaActionPerformed

    private void rbCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCentroActionPerformed
        // TODO add your handling code here:
        if(rbCentro.isSelected()){
           etNombre.setHorizontalAlignment(etNombre.CENTER);
        }
    }//GEN-LAST:event_rbCentroActionPerformed

    private void rbDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDerechaActionPerformed
        // TODO add your handling code here:
        if(rbDerecha.isSelected()){
            etNombre.setHorizontalAlignment(etNombre.RIGHT);
        }
    }//GEN-LAST:event_rbDerechaActionPerformed
    
    public void cbIsSelected(){
        Font styleFont = new Font("SegoeUI", Font.BOLD|Font.ITALIC,12);
        if(cbCursiva.isSelected()&& cbNegrita.isSelected()){
            etNombre.setFont(styleFont);
        } else if (cbCursiva.isSelected()){
            styleFont = new Font("SegoeUI", Font.ITALIC,12);
            etNombre.setFont(styleFont);
        } else if (cbNegrita.isSelected()){
            styleFont = new Font("SegoeUI",Font.BOLD,12);
            etNombre.setFont(styleFont);
        } else {
            etNombre.setFont(font);
        }
    }
    
    private void cbCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursivaActionPerformed
        // TODO add your handling code here:
        cbIsSelected();
    }//GEN-LAST:event_cbCursivaActionPerformed

    private void cbNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNegritaActionPerformed
        // TODO add your handling code here:
        cbIsSelected();
    }//GEN-LAST:event_cbNegritaActionPerformed

    private void bAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAutorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Creado por Christian Mengibar Castillo.");
    }//GEN-LAST:event_bAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TratamientoDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TratamientoDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TratamientoDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TratamientoDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TratamientoDeTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAutor;
    private javax.swing.ButtonGroup bgAlineacion;
    private javax.swing.ButtonGroup bgFondo;
    private javax.swing.JCheckBox cbCursiva;
    private javax.swing.JCheckBox cbNegrita;
    private javax.swing.JTextField etNombre;
    private javax.swing.JLabel lAlineacion;
    private javax.swing.JLabel lFondo;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JRadioButton rbCentro;
    private javax.swing.JRadioButton rbDerecha;
    private javax.swing.JRadioButton rbIzquierda;
    private javax.swing.JRadioButton rbRojo;
    private javax.swing.JRadioButton rbVerde;
    // End of variables declaration//GEN-END:variables
}
