/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.radiobutton;

import javax.swing.JOptionPane;

/**
 *
 * @author CristinaPalaciosVall
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanelRadioButton = new javax.swing.JPanel();
        jRadioButtonTelevision = new javax.swing.JRadioButton();
        jRadioButtonInternet = new javax.swing.JRadioButton();
        jRadioButtonLibro = new javax.swing.JRadioButton();
        jPanelBotones = new javax.swing.JPanel();
        jButtonGo = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonFin = new javax.swing.JButton();
        jPanelCheckBox = new javax.swing.JPanel();
        jCheckBoxAleman = new javax.swing.JCheckBox();
        jCheckBoxIngles = new javax.swing.JCheckBox();
        jCheckBoxFrances = new javax.swing.JCheckBox();
        jCheckBoxEspanol = new javax.swing.JCheckBox();
        jLabelIdiomas = new javax.swing.JLabel();
        jComboBoxCoches = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecciona una de las 3 opciones:");

        jPanelRadioButton.setLayout(new java.awt.GridLayout(3, 1, 10, 20));

        buttonGroup.add(jRadioButtonTelevision);
        jRadioButtonTelevision.setText("Televisión");
        jPanelRadioButton.add(jRadioButtonTelevision);

        buttonGroup.add(jRadioButtonInternet);
        jRadioButtonInternet.setText("Internet");
        jPanelRadioButton.add(jRadioButtonInternet);

        buttonGroup.add(jRadioButtonLibro);
        jRadioButtonLibro.setText("Libro");
        jPanelRadioButton.add(jRadioButtonLibro);

        jPanelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jButtonGo.setText("Go");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonGo);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonReset);

        jButtonFin.setText("Finalizar");
        jButtonFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonFin);

        jPanelCheckBox.setLayout(new java.awt.GridLayout(4, 1, 10, 0));

        jCheckBoxAleman.setText("Alemán");
        jCheckBoxAleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAlemanActionPerformed(evt);
            }
        });
        jPanelCheckBox.add(jCheckBoxAleman);

        jCheckBoxIngles.setText("Inglés");
        jCheckBoxIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxInglesActionPerformed(evt);
            }
        });
        jPanelCheckBox.add(jCheckBoxIngles);

        jCheckBoxFrances.setText("Francés");
        jCheckBoxFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFrancesActionPerformed(evt);
            }
        });
        jPanelCheckBox.add(jCheckBoxFrances);

        jCheckBoxEspanol.setText("Español");
        jCheckBoxEspanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEspanolActionPerformed(evt);
            }
        });
        jPanelCheckBox.add(jCheckBoxEspanol);

        jComboBoxCoches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ford", "Nissan", "Volvo", "Subaru" }));
        jComboBoxCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCochesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabelIdiomas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxCoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        buttonGroup.clearSelection();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Finalizando aplicación");
        System.exit(WIDTH);
    }//GEN-LAST:event_jButtonFinActionPerformed

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        // TODO add your handling code here:
        Libro libro = new Libro(this, true);
        Internet internet = new Internet(this, true);
        Television television = new Television(this, true);
        
        if(jRadioButtonLibro.isSelected()) {
            libro.setVisible(true);
        } else if (jRadioButtonInternet.isSelected()) {
            internet.setVisible(true);
        } else if (jRadioButtonTelevision.isSelected()) {
            television.setVisible(true);
        } else {
            //mensaje
        }
    }//GEN-LAST:event_jButtonGoActionPerformed

    private void jCheckBoxAlemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAlemanActionPerformed
        // TODO add your handling code here:
        String texto = "Idiomas: ";
        
        if(jCheckBoxAleman.isSelected()) {
            texto += "Alemán, ";
        }
        
        if(jCheckBoxIngles.isSelected()) {
            texto += "Inglés, ";
        }
        
        if(jCheckBoxFrances.isSelected()) {
            texto += "Francés, ";
        }
        
        if(jCheckBoxEspanol.isSelected()) {
            texto += "Español, ";
        }
        
        texto = texto.substring(0, texto.length() - 2);
        jLabelIdiomas.setText(texto);
        
    }//GEN-LAST:event_jCheckBoxAlemanActionPerformed

    private void jCheckBoxInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxInglesActionPerformed
        // TODO add your handling code here:
              String texto = "Idiomas: ";
        
        if(jCheckBoxAleman.isSelected()) {
            texto += "Alemán, ";
        }
        
        if(jCheckBoxIngles.isSelected()) {
            texto += "Inglés, ";
        }
        
        if(jCheckBoxFrances.isSelected()) {
            texto += "Francés, ";
        }
        
        if(jCheckBoxEspanol.isSelected()) {
            texto += "Español, ";
        }
        
        texto = texto.substring(0, texto.length() - 2);
        jLabelIdiomas.setText(texto);
        
    }//GEN-LAST:event_jCheckBoxInglesActionPerformed

    private void jCheckBoxFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFrancesActionPerformed
        // TODO add your handling code here:
              String texto = "Idiomas: ";
        
        if(jCheckBoxAleman.isSelected()) {
            texto += "Alemán, ";
        }
        
        if(jCheckBoxIngles.isSelected()) {
            texto += "Inglés, ";
        }
        
        if(jCheckBoxFrances.isSelected()) {
            texto += "Francés, ";
        }
        
        if(jCheckBoxEspanol.isSelected()) {
            texto += "Español, ";
        }
        
        texto = texto.substring(0, texto.length() - 2);
        jLabelIdiomas.setText(texto);
        
    }//GEN-LAST:event_jCheckBoxFrancesActionPerformed

    private void jCheckBoxEspanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEspanolActionPerformed
        // TODO add your handling code here:
              String texto = "Idiomas: ";
        
        if(jCheckBoxAleman.isSelected()) {
            texto += "Alemán, ";
        }
        
        if(jCheckBoxIngles.isSelected()) {
            texto += "Inglés, ";
        }
        
        if(jCheckBoxFrances.isSelected()) {
            texto += "Francés, ";
        }
        
        if(jCheckBoxEspanol.isSelected()) {
            texto += "Español, ";
        }
        
        texto = texto.substring(0, texto.length() - 2);
        jLabelIdiomas.setText(texto);
        
    }//GEN-LAST:event_jCheckBoxEspanolActionPerformed

    private void jComboBoxCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCochesActionPerformed
        // TODO add your handling code here:
        // ford nissan volvo subaru
        String coche = "Coche seleccionado: ";
        if(evt.getSource() == jComboBoxCoches) {
            String chosen = (String) jComboBoxCoches.getSelectedItem();
            coche += chosen;
            jLabelIdiomas.setText(coche);
        }
        
    }//GEN-LAST:event_jComboBoxCochesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonFin;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JCheckBox jCheckBoxAleman;
    private javax.swing.JCheckBox jCheckBoxEspanol;
    private javax.swing.JCheckBox jCheckBoxFrances;
    private javax.swing.JCheckBox jCheckBoxIngles;
    private javax.swing.JComboBox<String> jComboBoxCoches;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIdiomas;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCheckBox;
    private javax.swing.JPanel jPanelRadioButton;
    private javax.swing.JRadioButton jRadioButtonInternet;
    private javax.swing.JRadioButton jRadioButtonLibro;
    private javax.swing.JRadioButton jRadioButtonTelevision;
    // End of variables declaration//GEN-END:variables
}
