/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.adivinarnumero2;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author UsuarioPC
 */
public class ScreenJuegoNumero extends javax.swing.JFrame {

    /**
     * Creates new form AdivinarNumero
     */
    public ScreenJuegoNumero() {
        initComponents();
        this.setLocationRelativeTo(null);
        btComprobar.setForeground(Color.PINK);
        btVolverelegirnumero.setForeground(Color.PINK);
        btComprobar.setBackground(Color.darkGray);
        btVolverelegirnumero.setBackground(Color.darkGray);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btComprobar = new javax.swing.JButton();
        TextFieldNumber = new javax.swing.JTextField();
        LabelInformation = new javax.swing.JLabel();
        btVolverelegirnumero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿QUE NUMERO CREES QUE ES?");

        btComprobar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btComprobar.setText("COMPROBAR");
        btComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprobarActionPerformed(evt);
            }
        });

        LabelInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btVolverelegirnumero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btVolverelegirnumero.setText("VOLVER A ELEGIR NUMERO");
        btVolverelegirnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverelegirnumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btVolverelegirnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(TextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btComprobar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVolverelegirnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprobarActionPerformed

        ScreenElegirNumero elegirNumero = new ScreenElegirNumero();
        Integer numberRandom = elegirNumero.myRandomNumber;

        String number;
        Integer num;

        try {

            if (TextFieldNumber.getText().isEmpty()) {
                LabelInformation.setText("Debes introducir un numero");

            } else {

                number = TextFieldNumber.getText();
                num = Integer.parseInt(number);

                if (numberRandom > num) {
                    LabelInformation.setText("El numero que buscas es mas grande que " + num);

                } else if (numberRandom < num) {
                    LabelInformation.setText("El numero que buscas es mas pequeño que " + num);

                } else {
                    JOptionPane.showMessageDialog(null, "Has adivinado el número");
                    ScreenNumeroAdivinado pa = new ScreenNumeroAdivinado(this, rootPaneCheckingEnabled);
                    pa.setVisible(true);
                    this.setVisible(false);

                }

            }

        } catch (NumberFormatException e) {
            LabelInformation.setText("El valor introducido no es valido");

        }

    }//GEN-LAST:event_btComprobarActionPerformed

    private void btVolverelegirnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverelegirnumeroActionPerformed
        ScreenElegirNumero elegirNumero = new ScreenElegirNumero();
        elegirNumero.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btVolverelegirnumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenJuegoNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenJuegoNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenJuegoNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenJuegoNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenJuegoNumero().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelInformation;
    private javax.swing.JTextField TextFieldNumber;
    private javax.swing.JButton btComprobar;
    private javax.swing.JButton btVolverelegirnumero;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
