/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.adivinarnumero2;

import java.awt.Color;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author UsuarioPC
 */
public class ScreenNumeroAdivinado extends javax.swing.JDialog {

    /**
     * Creates new form Adivinado
     */
    public ScreenNumeroAdivinado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        btElegirOtrosNumeros2.setForeground(Color.PINK);
        btVolverAMenu.setForeground(Color.PINK);
        btSalir2.setForeground(Color.PINK);

        btElegirOtrosNumeros2.setBackground(Color.darkGray);
        btVolverAMenu.setBackground(Color.darkGray);
        btSalir2.setBackground(Color.darkGray);

    }

    ScreenNumeroAdivinado() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    ScreenNumeroAdivinado(JDialog jDialog) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btElegirOtrosNumeros2 = new javax.swing.JButton();
        btVolverAMenu = new javax.swing.JButton();
        btSalir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btElegirOtrosNumeros2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btElegirOtrosNumeros2.setText("ELEGIR OTROS NÚMEROS");
        btElegirOtrosNumeros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElegirOtrosNumeros2ActionPerformed(evt);
            }
        });

        btVolverAMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btVolverAMenu.setText("VOLVER AL INICIO");
        btVolverAMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverAMenuActionPerformed(evt);
            }
        });

        btSalir2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSalir2.setText("SALIR");
        btSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btElegirOtrosNumeros2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btVolverAMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btElegirOtrosNumeros2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btVolverAMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btElegirOtrosNumeros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElegirOtrosNumeros2ActionPerformed
        ScreenElegirNumero elegirNumero = new ScreenElegirNumero();
        elegirNumero.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btElegirOtrosNumeros2ActionPerformed

    private void btVolverAMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverAMenuActionPerformed

        ScreenMenu screenMenu = new ScreenMenu();

        screenMenu.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_btVolverAMenuActionPerformed

    private void btSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenNumeroAdivinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenNumeroAdivinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenNumeroAdivinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenNumeroAdivinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ScreenNumeroAdivinado dialog = new ScreenNumeroAdivinado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btElegirOtrosNumeros2;
    private javax.swing.JButton btSalir2;
    private javax.swing.JButton btVolverAMenu;
    // End of variables declaration//GEN-END:variables
}
